name: yaman_scanner
description: Yaman Store SKU Scanner
publish_to: 'none'
version: 2.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Camera
  camera: ^0.10.5+9
  # ML Kit OCR
  google_mlkit_text_recognition: ^0.13.1
  # HTTP
  http: ^1.2.1
  # Local DB
  sqflite: ^2.3.3+1
  path: ^1.9.0
  # Vibration
  vibration: ^3.1.8
  # Shared prefs
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
